config/routes.rb
Papic::Application.routes.draw do
  filter :locale
  root :to => 'pages#index'
  get 'about' => 'pages#about', :as => :about
  get 'qa' => 'pages#qa', :as => :qa
  get 'contact' => 'pages#contact', :as => :contact
  get 'tutorial' => 'pages#tutorial', :as => :tutorial
  
  resources :users, :only => [:create, :show] do
    resources :user_profiles, :except => [:index, :show, :destroy]
  end
  resource :user, :only => [:edit, :update, :destroy]
  resources :user_sessions, :only => [:create]
  
  get     'signin'    => 'user_sessions#new'
  delete  'signout'   => 'user_sessions#destroy'
  get     'register'  => 'users#new'
  
  resource :contact, :only => [:new]
  resource :place, :only => [:new]
  
  resources :jobs, :except => [:destroy] do
    get 'page/:page', :action => :index, :on => :collection
    resources :resumes, :only => [:create, :update] do
      put :accept, :on => :collection
    end
  end
  
  resources :letters, :only => [:index, :create, :show] do
    get :autocomplete_user_login, :on => :collection
  end
  
  namespace :admin do
    resources :users, :only => [:index] do
      member do
        put :change_state
      end
      member do
        put :change_role
      end
    end
    resources :jobs, :only => [:destroy] do
      member do
        put :change_state
      end
    end
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  STATES = %w(invalid valid old)
  CATEGORIES = %w(tutor campus parttimes)
  
  has_many :resumes
  has_many :users, :through => :resumes
  has_one  :job_profile
  has_one  :user_profile
  has_one  :child_profile, :dependent => :delete
  
  validates_presence_of :name, :pay, :state, :category, 
    :job_profile, :user_profile
  validates_numericality_of :pay, :greater_than_or_equal_to => 0
  validates_inclusion_of :state, :in => STATES
  validates_inclusion_of :category,  :in => CATEGORIES
  
  accepts_nested_attributes_for :resumes
  accepts_nested_attributes_for :job_profile, :child_profile, :user_profile,
    :limit => 1
  
  attr_accessible :name, :pay, :category,
    :job_profile_attributes, :child_profile_attributes, :resumes_attributes
  attr_accessible :name, :pay, :category,
    :job_profile_attributes, :child_profile_attributes, :user_profile_attributes,
    :resumes_attributes, :as => :admin
  
  default_scope order('updated_at desc')
  scope :campus, where(:category => 'campus')
  scope :tutor, where(:category => 'tutor')
  scope :parttimes, where(:category => 'parttimes')
  scope :invalid, where(:state => 'invalid')
  scope :valid, where(:state => 'valid')
  scope :old, where(:state => 'old')
end




# == Schema Information
#
# Table name: jobs
#
#  id         :integer         not null, primary key
#  name       :string(20)      not null
#  pay        :decimal(, )     not null
#  state      :string(255)     not null
#  category   :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::AdminController
  def change_state
    @job = Job.find(params[:id])
    @job.state = params[:job][:state]
    @job.save
    respond_with @job
  end
  
  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    respond_with @job
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]
  before_filter :have_create_permission, :only => [:create]
  before_filter :have_checker_permission, :only => [:edit, :update]
  layout 'public', :only => [:index, :show]
  
  def index
    case params[:category]
    when 'campus' then @jobs = Job.campus.page(params[:page])
    when 'tutor'  then @jobs = Job.tutor.page(params[:page])
    when 'parttimes' then @jobs = Job.parttimes.page(params[:page])
    else @jobs = Job.page(params[:page])
    end
  end

  def show
    @job = Job.find(params[:id])
    if @job.state == 'valid' && current_user && !current_user.have_checker_permission_for(@job)
      @resume = @job.resumes.find_or_initialize_by_user_id(current_user.id)
    end
    @gmap = @job.job_profile.to_gmaps4rails
  end

  def new
    @category = params[:category] || 'campus'
    @job = Job.new(:category => @category)
    @job.build_job_profile
    if @category == 'tutor' then @job.build_child_profile end
    if current_user.is_admin?
      @job.build_user_profile
      case @category
      when 'campus' then @job.user_profile.build_student_profile
      when 'parttimes' then @job.user_profile.build_company_profile
      end
    end
    respond_with @job
  end

  def create
    if current_user.is_admin?
      @job = Job.new(params[:job], :as => :admin)
    else
      @job = Job.new(params[:job])
      @job.user_profile = current_user.user_profile
    end
    valid = current_user.can_create_valid_job_for?(@@category)
    @job.state = valid ? 'valid' : 'invalid'
    @job.save
    respond_with @job
  end

  def edit
    respond_with @job
  end

  def update
    @job.update_attributes(params[:job])
    respond_with @job
  end
  
  private
    def have_checker_permission
      @job = Job.find(params[:id])
      if !current_user.have_checker_permission_for(@job)
        redirect_to @job
      end
    end
    
    def have_create_permission
      @@category = params[:job][:category]
      if !current_user.can_create_job_for?(@@category)
        redirect_to new_job_url
      end
    end
end

app/views/jobs/_fields.html.haml
= f.input :name
= f.input :pay
= f.input :category, :as => :hidden

app/views/jobs/_form.html.haml
= simple_form_for @job, :html => {:class => 'form-horizontal' } do |f|
  = render 'fields', :f => f
  = render 'job_profiles/fields', :f => f,
    :locals => {:job_profile => @job.job_profile}
  - if @category == 'tutor'
    %h3= ChildProfile.model_name.human
    = render 'child_profiles/fields', :f => f,
      :locals => {:child_profile => @job.child_profile}
  - if current_user.is_admin?
    %h3= UserProfile.model_name.human
    = f.simple_fields_for :user_profile do |g|
      = render 'user_profiles/fields', :f => g,
        :locals => {:user_profile => @job.user_profile}
      - case @category
      - when 'parttimes' then
        %h3= CompanyProfile.model_name.human
        = render 'company_profiles/fields', :f => g,
          :locals => {:company_profile => @job.user_profile.company_profile}
      - when 'campus' then
        %h3= StudentProfile.model_name.human
        = render 'student_profiles/fields', :f => g,
          :locals => {:student_profile => @job.user_profile.student_profile}
  = f.button :submit

app/views/jobs/_job.html.haml
%table.table.table-striped
  %tr
    %td= Job.human_attribute_name('name')
    %td= @job.name
  %tr
    %td= Job.human_attribute_name('pay')
    %td= @job.pay
  %tr
    %td 申请统计
    %td= @job.resumes.count
  = render @job.job_profile

app/views/jobs/edit.html.haml
= render 'form'

app/views/jobs/index.html.haml
= paginate @jobs
%hr     
.tab-content
  .tab-pane.fade.active.in#all
    .accordion#accordion-all
      - @jobs.each do |job|
        .accordion-group
          .accordion-heading
            .accordion-toggle{"data-parent" => "#accordion-all", "data-toggle" => "collapse", "data-target" => "#job_#{job.id}"}
              %h2= job.name
          = div_for(job, :class => "accordion-body collapse in") do
            .accordion-inner
              = link_to 'Detail', job_url(job)

= paginate @jobs
%hr

- if current_user && current_user.is_admin?
  = link_to "NewJob", new_job_path

app/views/jobs/new.html.haml
%h2= t('.create_parttimes')
= render 'form'

app/views/jobs/show.html.haml
= render @job  
= gmaps4rails(@gmap)  

%hr
  
- if current_user
  - case @job.state
  - when 'invalid'
    %p Invalid!
  - when 'valid'
    - if current_user.have_checker_permission_for(@job)
      .btn-group
        = link_to t('edit'), edit_job_path(@job), :class => "btn btn-info"
        = link_to t('destroy'), @job, :confirm => t('confirm'), :class => "btn btn-danger", :method => :delete
      - if @job.resumes.count >= @job.job_profile.amount      
        %p.well
          已接受人数：
          = @job.resumes.accepted.count
        = render 'resumes/form_for_accept'
    - else
      = render 'resumes/form'
  - when 'old'
    %p Old