config/routes.rb
Papic::Application.routes.draw do
  filter :locale
  root :to => 'pages#index'
  get 'about' => 'pages#about', :as => :about
  get 'qa' => 'pages#qa', :as => :qa
  get 'contact' => 'pages#contact', :as => :contact
  get 'tutorial' => 'pages#tutorial', :as => :tutorial
  
  resources :users, :only => [:create, :show] do
    resources :user_profiles, :except => [:index, :show, :destroy]
  end
  resource :user, :only => [:edit, :update, :destroy]
  resources :user_sessions, :only => [:create]
  
  get     'signin'    => 'user_sessions#new'
  delete  'signout'   => 'user_sessions#destroy'
  get     'register'  => 'users#new'
  
  resource :contact, :only => [:new]
  resource :place, :only => [:new]
  
  resources :jobs, :except => [:destroy] do
    get 'page/:page', :action => :index, :on => :collection
    resources :resumes, :only => [:create, :update] do
      put :accept, :on => :collection
    end
  end
  
  resources :letters, :only => [:index, :create, :show] do
    get :autocomplete_user_login, :on => :collection
  end
  
  namespace :admin do
    resources :users, :only => [:index] do
      member do
        put :change_state
      end
      member do
        put :change_role
      end
    end
    resources :jobs, :only => [:destroy] do
      member do
        put :change_state
      end
    end
  end
end

app/views/layouts/_flashes.html.haml
- [:notice, :error, :alert].each do |level|
  - unless flash[level].blank?
    %div{:class => "alert alert-#{level.to_s}"}
      %a.close{"data-dismiss" => "alert"}×
      = flash[level]

app/views/layouts/_footer.html.haml
%hr
%footer.nice-footer
  %p
    = link_to t(".about"), about_url
    \|
    = link_to t(".qa"), qa_url
    \|
    = link_to t(".contact"), contact_url
  %p &copy; 浙江大学勤工俭学与创业实践指导中心 2012 - 2012

app/views/layouts/_header.html.haml
.row
  .span3
    = link_to image_tag('logo.png', :mouseover => image_path('logo_red.png')), root_url

%ul.nav.nav-tabs
  %li.active= link_to t(".root"), root_url
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      = t(".jobs")
      %b.caret
    %ul.dropdown-menu
      - Job::CATEGORIES.each do |category|
        = link_to Job.human_attribute_name(category), jobs_url(:category => category)
  - if current_user
    %li.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        = t(".new_job")
        %b.caret
      %ul.dropdown-menu      
        - Job::CATEGORIES.each do |category|
          - if current_user.can_create_job_for?(category)
            %li= link_to t(".new_#{category}_jobs"), new_job_url(:category => category)
    %li= link_to t(".letter"), letters_url
  .pull-right
    - if current_user
      %span.label        
        &nbsp;
        = t('.welcome_back') + ","
        = link_to current_user.login, user_url(current_user)  
        &nbsp;
      %span.label.label-warning  
        &nbsp;
        = link_to t('.signout'), signout_path, :method => :delete  
        &nbsp;
    - else
      %span.label.label-info
        &nbsp;
        = link_to t('.signin'),   '#signin', "data-toggle" => "modal"
        \|
        = link_to t('.register'), register_path
        &nbsp;

.modal.fade#signin
  .modal-header
    %a.close{"data-dismiss" => "modal"} x
    %h3= t('.signin')
  = simple_form_for UserSession.new, :html => {:class => 'form-horizontal'} do |f|
    .modal-body
      = f.input :login
      = f.input :password
    .modal-footer 
      .btn.btn-danger
        %a.close{"data-dismiss" => "modal"}= t('cancel')
      = f.button :submit, t('.signin'), :class => 'btn-primary'      

app/views/layouts/_sidebar.html.haml
.well.sidebar-nav
  %ul.nav.nav-list
    - if current_user
      %li.nav-header= User.model_name.human
      - if current_user.user_profile
        = image_tag current_user.user_profile.avatar.url(:thumb)
        %li= link_to t('.edit_user_profile'), edit_user_user_profile_url(current_user, current_user.user_profile)
      - else
        %li= link_to t('.new_user_profile'), new_user_user_profile_url(current_user)
/ well

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : t('.papic')
    = csrf_meta_tags
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %meta{:name => "description", :content => ""}
    %meta{:name => "author", :content => ""}
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    / Le styles
    = stylesheet_link_tag "application", :media => "all"
    / Le fav
    %link{:href => "/assets/favicon.ico", :rel => "shortcut icon"}

  %body
    .container-fluid
    
      = render 'layouts/header'
      
      .content
        .row-fluid
          .span3= render 'layouts/sidebar'
          .span9
            = render 'layouts/flashes'
            = yield
      
    = render 'layouts/footer'
      
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = yield :scripts

app/views/layouts/public.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : t('.papic')
    = csrf_meta_tags
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %meta{:name => "description", :content => ""}
    %meta{:name => "author", :content => ""}
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    / Le styles
    = stylesheet_link_tag "application", :media => "all"
    / Le fav
    %link{:href => "/assets/favicon.ico", :rel => "shortcut icon"}

  %body
    .container-fluid
    
      = render 'layouts/header'
    
      .content
        .row-fluid
          = render 'layouts/flashes'
          = yield
    
    = render 'layouts/footer'
      
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = yield :scripts